[package]
name = "avaro"
description = "a plain text double-accounting tool which is compatible with beancount but more powerful"
licese = "MIT"
version = "0.0.1"
authors = ["Kilerd <blove694@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
